language: swift
osx_image: xcode10.1

script:
  - pkgutil --packages
  - sudo softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1"
  - brew tap wix/brew
  - brew install applesimutils
